insert into public.cryptotokens (
    id,
    token_name,
    cmc_link,
    home_link,
    x_link,
    priority
) values
(1, 'BTC', 'bitcoin/', 'bitcoin.org/', 'bitcoin', 1),
(2, 'ETH', 'ethereum/', 'ethereum.org/', 'ethereum', 2),
(3, 'USDT', 'tether/', 'tether.to/', 'tether_to', 3),
(4, 'BNB', 'bnb/', 'www.bnbchain.org/', 'bnbchain', 4),
(5, 'XRP', 'xrp/', 'ripple.com/xrp/', 'ripple', 5),
(6, 'USDC', 'usd-coin/', 'www.usdc.com/', 'usdc', 6),
(7, 'SOL', 'solana/', 'solana.com/', 'solana', 7),
(8, 'TRX', 'tron/', 'tron.network/', 'tronado', 8),
(9, 'DOGE', 'dogecoin/', 'dogecoin.com/', 'dogecoin', 9),
(10, 'ADA', 'cardano/', 'cardano.org/', 'cardano', 10),
(11, 'BCH', 'bitcoin-cash/', 'bitcoincash.org/', 'bitcoin-cash', 11),
(12, 'LINK', 'chainlink/', 'chain.link/', 'chainlink', 12),
(13, 'LIDO', 'lido-dao/', 'lido.fi/', 'lido-dao', 13),
(14, 'WBTC', 'wrapped-bitcoin/', 'wrapped.com/', 'wrapped-bitcoin', 14),
(15, 'DOT', 'polkadot-new/', 'polkadot.network/', 'polkadot', 15),
(16, 'AVAX', 'avalanche/', 'avax.network/', 'avalanche', 16),
(17, 'MATIC', 'polygon/', 'polygon.technology/', 'polygon', 17),
(18, 'SHIB', 'shiba-inu/', 'shibatoken.com/', 'shiba-inu', 18),
(19, 'STETH', 'steth/', '', 'steth', 19),
(20, 'XLM', 'stellar/', 'stellar.org/', 'stellar', 20),
(21, 'NEAR', 'near/', 'near.org/', 'near', 21),
(22, 'FTM', 'fantom/', 'fantom.foundation/', 'fantom', 22),
(23, 'APE', 'apecoin/', 'apecoin.com/', 'apecoin', 23),
(24, 'ICP', 'internet-computer/', 'dfinity.org/', 'internet-computer', 24),
(25, 'LTC', 'litecoin/', 'litecoin.org/', 'litecoin', 25),
(26, 'ATOM', 'cosmos/', 'cosmos.network/', 'cosmos', 26),
(27, 'MKR', 'maker/', 'makerdao.com/', 'maker', 27),
(28, 'XMR', 'monero/', 'getmonero.org/', 'monero', 28),
(29, 'EOS', 'eos/', 'eos.io/', 'eos', 29),
(30, 'QNT', 'quant/', 'quant.network/', 'quant', 30),
(31, 'ZEC', 'zcash/', 'zcash.org/', 'zcash', 31),
(32, 'STX', 'stacks/', 'stacks.co/', 'stacks', 32),
(33, 'FLOW', 'flow/', 'onflow.org/', 'flow', 33),
(34, 'CEL', 'celsius/', 'celsius.network/', 'celsius', 34),
(35, 'GRT', 'the-graph/', 'thegraph.com/', 'the-graph', 35),
(36, 'AR', 'arweave/', 'arweave.org/', 'arweave', 36),
(37, 'SAND', 'the-sandbox/', 'sandbox.game/', 'the-sandbox', 37),
(38, 'AAVE', 'aave/', 'aave.com/', 'aave', 38),
(39, 'MIOTA', 'iota/', 'iota.org/', 'iota', 39),
(40, 'NEO', 'neo/', 'neo.org/', 'neo', 40),
(41, 'HT', 'huobi-token/', 'huobi.com/', 'huobi-token', 41),
(42, 'KCS', 'kucoin-token/', 'kucoin.com/', 'kucoin-token', 42),
(43, 'CRV', 'curve-dao-token/', 'curve.fi/', 'curve-dao-token', 43),
(44, 'API3', 'api3/', 'api3.org/', 'api3', 44),
(45, 'ZIL', 'zilliqa/', 'zilliqa.com/', 'zilliqa', 45),
(46, 'DASH', 'dash/', 'dash.org/', 'dash', 46),
(47, 'ONT', 'ontology/', 'ontology.io/', 'ontology', 47),
(48, 'KLAY', 'klay-token/', 'klaytn.foundation/', 'klay-token', 48),
(49, 'CHZ', 'chiliz/', 'chiliz.com/', 'chiliz', 49),
(50, 'VET', 'vechain/', 'vechain.org/', 'vechain', 50)
on conflict (id) do nothing;


