/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./__root";
import { Route as IndexRouteImport } from "./index";
import { Route as AuthVerifyRouteImport } from "./auth/verify";
import { Route as AuthProfileRouteImport } from "./auth/profile";
import { Route as AuthEmailRouteImport } from "./auth/email";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: "/auth/verify",
  path: "/auth/verify",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthProfileRoute = AuthProfileRouteImport.update({
  id: "/auth/profile",
  path: "/auth/profile",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthEmailRoute = AuthEmailRouteImport.update({
  id: "/auth/email",
  path: "/auth/email",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/auth/email": typeof AuthEmailRoute;
  "/auth/profile": typeof AuthProfileRoute;
  "/auth/verify": typeof AuthVerifyRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/auth/email": typeof AuthEmailRoute;
  "/auth/profile": typeof AuthProfileRoute;
  "/auth/verify": typeof AuthVerifyRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/auth/email": typeof AuthEmailRoute;
  "/auth/profile": typeof AuthProfileRoute;
  "/auth/verify": typeof AuthVerifyRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/auth/email" | "/auth/profile" | "/auth/verify";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/auth/email" | "/auth/profile" | "/auth/verify";
  id: "__root__" | "/" | "/auth/email" | "/auth/profile" | "/auth/verify";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AuthEmailRoute: typeof AuthEmailRoute;
  AuthProfileRoute: typeof AuthProfileRoute;
  AuthVerifyRoute: typeof AuthVerifyRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/auth/verify": {
      id: "/auth/verify";
      path: "/auth/verify";
      fullPath: "/auth/verify";
      preLoaderRoute: typeof AuthVerifyRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/auth/profile": {
      id: "/auth/profile";
      path: "/auth/profile";
      fullPath: "/auth/profile";
      preLoaderRoute: typeof AuthProfileRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/auth/email": {
      id: "/auth/email";
      path: "/auth/email";
      fullPath: "/auth/email";
      preLoaderRoute: typeof AuthEmailRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthEmailRoute: AuthEmailRoute,
  AuthProfileRoute: AuthProfileRoute,
  AuthVerifyRoute: AuthVerifyRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
