/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./__root";
import { Route as ProfileRouteImport } from "./profile";
import { Route as IndexRouteImport } from "./index";
import { Route as ProfileUnlikedpostsRouteImport } from "./profile/unlikedposts";
import { Route as ProfileMainRouteImport } from "./profile/main";
import { Route as ProfileLikespostsRouteImport } from "./profile/likesposts";
import { Route as ProfileFavoritevideosRouteImport } from "./profile/favoritevideos";
import { Route as ProfileEditnameRouteImport } from "./profile/editname";
import { Route as ProfileCryptohuberRouteImport } from "./profile/cryptohuber";
import { Route as AuthVerifyRouteImport } from "./auth/verify";
import { Route as AuthSavenicknameRouteImport } from "./auth/savenickname";
import { Route as AuthEmailRouteImport } from "./auth/email";
import { Route as AuthCallbackRouteImport } from "./auth/callback";

const ProfileRoute = ProfileRouteImport.update({
  id: "/profile",
  path: "/profile",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const ProfileUnlikedpostsRoute = ProfileUnlikedpostsRouteImport.update({
  id: "/unlikedposts",
  path: "/unlikedposts",
  getParentRoute: () => ProfileRoute,
} as any);
const ProfileMainRoute = ProfileMainRouteImport.update({
  id: "/main",
  path: "/main",
  getParentRoute: () => ProfileRoute,
} as any);
const ProfileLikespostsRoute = ProfileLikespostsRouteImport.update({
  id: "/likesposts",
  path: "/likesposts",
  getParentRoute: () => ProfileRoute,
} as any);
const ProfileFavoritevideosRoute = ProfileFavoritevideosRouteImport.update({
  id: "/favoritevideos",
  path: "/favoritevideos",
  getParentRoute: () => ProfileRoute,
} as any);
const ProfileEditnameRoute = ProfileEditnameRouteImport.update({
  id: "/editname",
  path: "/editname",
  getParentRoute: () => ProfileRoute,
} as any);
const ProfileCryptohuberRoute = ProfileCryptohuberRouteImport.update({
  id: "/cryptohuber",
  path: "/cryptohuber",
  getParentRoute: () => ProfileRoute,
} as any);
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: "/auth/verify",
  path: "/auth/verify",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthSavenicknameRoute = AuthSavenicknameRouteImport.update({
  id: "/auth/savenickname",
  path: "/auth/savenickname",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthEmailRoute = AuthEmailRouteImport.update({
  id: "/auth/email",
  path: "/auth/email",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: "/auth/callback",
  path: "/auth/callback",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/profile": typeof ProfileRouteWithChildren;
  "/auth/callback": typeof AuthCallbackRoute;
  "/auth/email": typeof AuthEmailRoute;
  "/auth/savenickname": typeof AuthSavenicknameRoute;
  "/auth/verify": typeof AuthVerifyRoute;
  "/profile/cryptohuber": typeof ProfileCryptohuberRoute;
  "/profile/editname": typeof ProfileEditnameRoute;
  "/profile/favoritevideos": typeof ProfileFavoritevideosRoute;
  "/profile/likesposts": typeof ProfileLikespostsRoute;
  "/profile/main": typeof ProfileMainRoute;
  "/profile/unlikedposts": typeof ProfileUnlikedpostsRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/profile": typeof ProfileRouteWithChildren;
  "/auth/callback": typeof AuthCallbackRoute;
  "/auth/email": typeof AuthEmailRoute;
  "/auth/savenickname": typeof AuthSavenicknameRoute;
  "/auth/verify": typeof AuthVerifyRoute;
  "/profile/cryptohuber": typeof ProfileCryptohuberRoute;
  "/profile/editname": typeof ProfileEditnameRoute;
  "/profile/favoritevideos": typeof ProfileFavoritevideosRoute;
  "/profile/likesposts": typeof ProfileLikespostsRoute;
  "/profile/main": typeof ProfileMainRoute;
  "/profile/unlikedposts": typeof ProfileUnlikedpostsRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/profile": typeof ProfileRouteWithChildren;
  "/auth/callback": typeof AuthCallbackRoute;
  "/auth/email": typeof AuthEmailRoute;
  "/auth/savenickname": typeof AuthSavenicknameRoute;
  "/auth/verify": typeof AuthVerifyRoute;
  "/profile/cryptohuber": typeof ProfileCryptohuberRoute;
  "/profile/editname": typeof ProfileEditnameRoute;
  "/profile/favoritevideos": typeof ProfileFavoritevideosRoute;
  "/profile/likesposts": typeof ProfileLikespostsRoute;
  "/profile/main": typeof ProfileMainRoute;
  "/profile/unlikedposts": typeof ProfileUnlikedpostsRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/profile"
    | "/auth/callback"
    | "/auth/email"
    | "/auth/savenickname"
    | "/auth/verify"
    | "/profile/cryptohuber"
    | "/profile/editname"
    | "/profile/favoritevideos"
    | "/profile/likesposts"
    | "/profile/main"
    | "/profile/unlikedposts";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/profile"
    | "/auth/callback"
    | "/auth/email"
    | "/auth/savenickname"
    | "/auth/verify"
    | "/profile/cryptohuber"
    | "/profile/editname"
    | "/profile/favoritevideos"
    | "/profile/likesposts"
    | "/profile/main"
    | "/profile/unlikedposts";
  id:
    | "__root__"
    | "/"
    | "/profile"
    | "/auth/callback"
    | "/auth/email"
    | "/auth/savenickname"
    | "/auth/verify"
    | "/profile/cryptohuber"
    | "/profile/editname"
    | "/profile/favoritevideos"
    | "/profile/likesposts"
    | "/profile/main"
    | "/profile/unlikedposts";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  ProfileRoute: typeof ProfileRouteWithChildren;
  AuthCallbackRoute: typeof AuthCallbackRoute;
  AuthEmailRoute: typeof AuthEmailRoute;
  AuthSavenicknameRoute: typeof AuthSavenicknameRoute;
  AuthVerifyRoute: typeof AuthVerifyRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/profile": {
      id: "/profile";
      path: "/profile";
      fullPath: "/profile";
      preLoaderRoute: typeof ProfileRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/profile/unlikedposts": {
      id: "/profile/unlikedposts";
      path: "/unlikedposts";
      fullPath: "/profile/unlikedposts";
      preLoaderRoute: typeof ProfileUnlikedpostsRouteImport;
      parentRoute: typeof ProfileRoute;
    };
    "/profile/main": {
      id: "/profile/main";
      path: "/main";
      fullPath: "/profile/main";
      preLoaderRoute: typeof ProfileMainRouteImport;
      parentRoute: typeof ProfileRoute;
    };
    "/profile/likesposts": {
      id: "/profile/likesposts";
      path: "/likesposts";
      fullPath: "/profile/likesposts";
      preLoaderRoute: typeof ProfileLikespostsRouteImport;
      parentRoute: typeof ProfileRoute;
    };
    "/profile/favoritevideos": {
      id: "/profile/favoritevideos";
      path: "/favoritevideos";
      fullPath: "/profile/favoritevideos";
      preLoaderRoute: typeof ProfileFavoritevideosRouteImport;
      parentRoute: typeof ProfileRoute;
    };
    "/profile/editname": {
      id: "/profile/editname";
      path: "/editname";
      fullPath: "/profile/editname";
      preLoaderRoute: typeof ProfileEditnameRouteImport;
      parentRoute: typeof ProfileRoute;
    };
    "/profile/cryptohuber": {
      id: "/profile/cryptohuber";
      path: "/cryptohuber";
      fullPath: "/profile/cryptohuber";
      preLoaderRoute: typeof ProfileCryptohuberRouteImport;
      parentRoute: typeof ProfileRoute;
    };
    "/auth/verify": {
      id: "/auth/verify";
      path: "/auth/verify";
      fullPath: "/auth/verify";
      preLoaderRoute: typeof AuthVerifyRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/auth/savenickname": {
      id: "/auth/savenickname";
      path: "/auth/savenickname";
      fullPath: "/auth/savenickname";
      preLoaderRoute: typeof AuthSavenicknameRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/auth/email": {
      id: "/auth/email";
      path: "/auth/email";
      fullPath: "/auth/email";
      preLoaderRoute: typeof AuthEmailRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/auth/callback": {
      id: "/auth/callback";
      path: "/auth/callback";
      fullPath: "/auth/callback";
      preLoaderRoute: typeof AuthCallbackRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

interface ProfileRouteChildren {
  ProfileCryptohuberRoute: typeof ProfileCryptohuberRoute;
  ProfileEditnameRoute: typeof ProfileEditnameRoute;
  ProfileFavoritevideosRoute: typeof ProfileFavoritevideosRoute;
  ProfileLikespostsRoute: typeof ProfileLikespostsRoute;
  ProfileMainRoute: typeof ProfileMainRoute;
  ProfileUnlikedpostsRoute: typeof ProfileUnlikedpostsRoute;
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfileCryptohuberRoute: ProfileCryptohuberRoute,
  ProfileEditnameRoute: ProfileEditnameRoute,
  ProfileFavoritevideosRoute: ProfileFavoritevideosRoute,
  ProfileLikespostsRoute: ProfileLikespostsRoute,
  ProfileMainRoute: ProfileMainRoute,
  ProfileUnlikedpostsRoute: ProfileUnlikedpostsRoute,
};

const ProfileRouteWithChildren = ProfileRoute._addFileChildren(
  ProfileRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProfileRoute: ProfileRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthEmailRoute: AuthEmailRoute,
  AuthSavenicknameRoute: AuthSavenicknameRoute,
  AuthVerifyRoute: AuthVerifyRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
