services:
  pgadmin:
    image: dpage/pgadmin4
    container_name: crypto_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: cryptohub1112@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
