import { useState } from "react";
import { useFiltersStore } from "@/store/useFiltersStore";
import { motion, AnimatePresence } from "framer-motion";
import { useTokensAiForecasts } from "@/api/useTokensAiForecasts";
import { useEscapeKey } from "@/hooks/useEscapeKey";

export default function TokensAiForecasts() {
  const { selectedToken } = useFiltersStore();
  const [open, setOpen] = useState(false);

  const { data: forecast, isLoading, error, refetch } = useTokensAiForecasts();
  if (error) console.error("Ошибка загрузки прогноза", error.message);

  const handleOpen = async () => {
    if (!selectedToken) return;
    const { data } = await refetch();
    if (data) setOpen(true);
    else alert("❌ Прогноз для этой монеты пока не доступен.");
  };

  useEscapeKey(() => setOpen(false));

  const handleBackdropClick = (e: React.MouseEvent<HTMLDivElement>) => {
    if (e.target === e.currentTarget) setOpen(false);
  };

  return (
    <>
      {/* 🔹 Кнопка для открытия модалки */}
      <button
        onClick={handleOpen}
        disabled={!selectedToken || isLoading}
        className="px-4 py-2 font-semibold text-white transition bg-green-600 rounded-lg shadow-md hover:bg-green-500 disabled:opacity-50"
      >
        {isLoading ? "Загрузка..." : "📈 Прогноз AI"}
      </button>

      {/* 🔹 Модалка */}
      <AnimatePresence>
        {open && forecast && (
          <motion.div
            className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 backdrop-blur-sm"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            onClick={handleBackdropClick}
          >
            <motion.div
              initial={{ opacity: 0, scale: 0.95 }}
              animate={{ opacity: 1, scale: 1 }}
              exit={{ opacity: 0, scale: 0.95 }}
              transition={{ duration: 0.2 }}
              className="bg-[#0f0f0f] text-gray-100 rounded-2xl p-6 w-[90%] max-w-[550px] max-h-[80vh] relative shadow-2xl border border-gray-800 overflow-hidden flex flex-col"
            >
              {/* Кнопка закрытия */}
              <button
                onClick={() => setOpen(false)}
                className="absolute text-xl text-gray-400 top-3 right-3 hover:text-white"
              >
                ✖
              </button>

              <h2 className="mb-3 text-xl font-bold text-center text-white">
                Прогноз по {forecast.token_name}
              </h2>

              <div className="flex justify-center mb-3">
                <span
                  className={`px-3 py-1 rounded-full text-sm ${
                    forecast.sentiment === "positive"
                      ? "bg-green-600/20 text-green-400"
                      : forecast.sentiment === "negative"
                        ? "bg-red-600/20 text-red-400"
                        : "bg-gray-600/20 text-gray-400"
                  }`}
                >
                  {forecast.sentiment}
                </span>
              </div>

              {/* Прокручиваемый блок текста */}
              <div className="flex-1 pr-1 overflow-y-auto custom-scroll">
                <p className="leading-relaxed text-center text-gray-200 whitespace-pre-wrap">
                  {forecast.forecast_text}
                </p>
              </div>

              {/* Подпись */}
              <p className="mt-4 text-xs italic text-center text-gray-600">
                Generated by AI 🤖
              </p>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>
    </>
  );
}

//TokensAIForecast
