import { useState } from 'react';
import CloseIcon from '@mui/icons-material/Close';
import {
  Box,
  Button,
  Chip,
  CircularProgress,
  Dialog,
  DialogContent,
  DialogTitle,
  IconButton,
  Stack,
  Typography,
} from '@mui/material';

import { useToast } from '@/hooks/useToast';
import {
  type TokenForecast,
  useTokensAiForecasts,
} from '@/routes/tokens/-api/useTokensAiForecasts';
import { useSelectedToken } from '@/store/useFiltersStore';
import { getErrorMessage } from '@/utils/errorUtils';

export default function TokensAiForecasts() {
  const { selectedToken } = useSelectedToken();
  const [open, setOpen] = useState(false);
  const { showError } = useToast();

  const { data: forecastData, isLoading, refetch } = useTokensAiForecasts();
  const forecast = forecastData ?? null;

  const handleOpen = async () => {
    if (!selectedToken) return;

    if (forecast) {
      setOpen(true);
      return;
    }

    try {
      const { data } = await refetch();
      if (data) {
        setOpen(true);
      } else {
        showError('Forecast for this token is not available yet.');
      }
    } catch (err) {
      showError(getErrorMessage(err, 'Failed to load forecast. Please try again later.'));
    }
  };

  return (
    <>
      <Button
        onClick={async () => handleOpen()}
        disabled={!selectedToken || isLoading}
        variant="contained"
        sx={buttonForecastStyles}
      >
        {isLoading ? (
          <Box display="flex" alignItems="center" gap={1}>
            <CircularProgress size={16} sx={{ color: '#fff' }} />
            Loading...
          </Box>
        ) : (
          '📈 AI Forecast'
        )}
      </Button>

      <Dialog
        open={open}
        onClose={() => {
          setOpen(false);
        }}
        maxWidth="sm"
        fullWidth
        slotProps={{
          backdrop: {
            sx: {
              backgroundColor: 'rgba(0, 0, 0, 0.8)',
              backdropFilter: 'blur(4px)',
              dialogPaperSx,
            },
          },
        }}
      >
        <DialogTitle sx={forecastModalStyles}>
          <Typography variant="h6" fontWeight={600}>
            {forecast === null ? 'AI Forecast' : `Forecast for ${selectedToken?.value}`}
          </Typography>
          <IconButton
            onClick={() => {
              setOpen(false);
            }}
            size="small"
            sx={closeButtonSx}
          >
            <CloseIcon />
          </IconButton>
        </DialogTitle>

        <DialogContent sx={forecastModalItemStyles}>
          {forecast !== null && <ForecastContent forecast={forecast} />}
        </DialogContent>
      </Dialog>
    </>
  );
}

function ForecastContent({ forecast }: { forecast: TokenForecast }) {
  const sentiment = forecast.sentiment || 'neutral';
  const sentimentColor = SENTIMENT_COLORS[sentiment] ?? SENTIMENT_COLORS.neutral;

  return (
    <Stack spacing={2} alignItems="center">
      <Chip
        label={sentiment}
        sx={{ ...sentimentColor, fontWeight: 500, textTransform: 'capitalize' }}
      />

      <Typography
        variant="body1"
        sx={{
          color: '#e5e7eb',
          lineHeight: 1.8,
          whiteSpace: 'pre-wrap',
          textAlign: 'center',
        }}
      >
        {forecast.forecast_text}
      </Typography>

      <Typography variant="caption" sx={{ color: '#6b7280', fontStyle: 'italic' }}>
        Generated by AI
      </Typography>
    </Stack>
  );
}

const buttonForecastStyles = {
  backgroundColor: '#0f0f0f',
  color: '#fafafa',
  border: '1px solid #262626',
  boxShadow: '0 1px 2px rgba(0, 0, 0, 0.4)',
  '&:hover': {
    backgroundColor: '#171717',
    borderColor: '#404040',
    boxShadow: '0 2px 8px rgba(0, 0, 0, 0.5)',
  },
  '&.Mui-disabled': {
    backgroundColor: 'rgba(15, 15, 15, 0.6)',
    color: 'rgba(250, 250, 250, 0.5)',
    borderColor: '#262626',
  },
};

const forecastModalStyles = {
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'space-between',
  borderBottom: '1px solid #27272a',
  pb: 2,
  color: '#fff',
};

const forecastModalItemStyles = {
  display: 'flex',
  flexDirection: 'column',
  gap: 2,
  pt: 3,
  color: '#fff',
  overflowY: 'auto',
  '&::-webkit-scrollbar': {
    width: '8px',
  },
  '&::-webkit-scrollbar-track': {
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderRadius: '4px',
  },
  '&::-webkit-scrollbar-thumb': {
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    borderRadius: '4px',
    '&:hover': {
      backgroundColor: 'rgba(255, 255, 255, 0.3)',
    },
  },
};

const SENTIMENT_COLORS: Record<
  string,
  { bgcolor: string; color: string; border: string }
> = {
  positive: {
    bgcolor: 'rgba(34, 197, 94, 0.1)',
    color: '#22c55e',
    border: '1px solid rgba(34, 197, 94, 0.3)',
  },
  negative: {
    bgcolor: 'rgba(239, 68, 68, 0.1)',
    color: '#ef4444',
    border: '1px solid rgba(239, 68, 68, 0.3)',
  },
  neutral: {
    bgcolor: 'rgba(156, 163, 175, 0.1)',
    color: '#9ca3af',
    border: '1px solid rgba(156, 163, 175, 0.3)',
  },
};

const dialogPaperSx = {
  background: 'linear-gradient(to bottom, #18181b, #000)',
  border: '1px solid #27272a',
  borderRadius: '16px',
  maxHeight: '80vh',
  display: 'flex',
  flexDirection: 'column',
};

const closeButtonSx = {
  color: '#a1a1aa',
  '&:hover': {
    color: '#fff',
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
  },
};
