/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./__root";
import { Route as IndexRouteImport } from "./index";
import { Route as NotificationsIndexRouteImport } from "./notifications/index";
import { Route as ForecastsIndexRouteImport } from "./forecasts/index";
import { Route as AuthIndexRouteImport } from "./auth/index";
import { Route as AuthVerifyRouteImport } from "./auth/verify";
import { Route as AuthCallbackRouteImport } from "./auth/callback";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const NotificationsIndexRoute = NotificationsIndexRouteImport.update({
  id: "/notifications/",
  path: "/notifications/",
  getParentRoute: () => rootRouteImport,
} as any);
const ForecastsIndexRoute = ForecastsIndexRouteImport.update({
  id: "/forecasts/",
  path: "/forecasts/",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: "/auth/",
  path: "/auth/",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: "/auth/verify",
  path: "/auth/verify",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: "/auth/callback",
  path: "/auth/callback",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/auth/callback": typeof AuthCallbackRoute;
  "/auth/verify": typeof AuthVerifyRoute;
  "/auth/": typeof AuthIndexRoute;
  "/forecasts/": typeof ForecastsIndexRoute;
  "/notifications/": typeof NotificationsIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/auth/callback": typeof AuthCallbackRoute;
  "/auth/verify": typeof AuthVerifyRoute;
  "/auth": typeof AuthIndexRoute;
  "/forecasts": typeof ForecastsIndexRoute;
  "/notifications": typeof NotificationsIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/auth/callback": typeof AuthCallbackRoute;
  "/auth/verify": typeof AuthVerifyRoute;
  "/auth/": typeof AuthIndexRoute;
  "/forecasts/": typeof ForecastsIndexRoute;
  "/notifications/": typeof NotificationsIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/auth/callback"
    | "/auth/verify"
    | "/auth/"
    | "/forecasts/"
    | "/notifications/";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/auth/callback"
    | "/auth/verify"
    | "/auth"
    | "/forecasts"
    | "/notifications";
  id:
    | "__root__"
    | "/"
    | "/auth/callback"
    | "/auth/verify"
    | "/auth/"
    | "/forecasts/"
    | "/notifications/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AuthCallbackRoute: typeof AuthCallbackRoute;
  AuthVerifyRoute: typeof AuthVerifyRoute;
  AuthIndexRoute: typeof AuthIndexRoute;
  ForecastsIndexRoute: typeof ForecastsIndexRoute;
  NotificationsIndexRoute: typeof NotificationsIndexRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/notifications/": {
      id: "/notifications/";
      path: "/notifications";
      fullPath: "/notifications/";
      preLoaderRoute: typeof NotificationsIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/forecasts/": {
      id: "/forecasts/";
      path: "/forecasts";
      fullPath: "/forecasts/";
      preLoaderRoute: typeof ForecastsIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/auth/": {
      id: "/auth/";
      path: "/auth";
      fullPath: "/auth/";
      preLoaderRoute: typeof AuthIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/auth/verify": {
      id: "/auth/verify";
      path: "/auth/verify";
      fullPath: "/auth/verify";
      preLoaderRoute: typeof AuthVerifyRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/auth/callback": {
      id: "/auth/callback";
      path: "/auth/callback";
      fullPath: "/auth/callback";
      preLoaderRoute: typeof AuthCallbackRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthVerifyRoute: AuthVerifyRoute,
  AuthIndexRoute: AuthIndexRoute,
  ForecastsIndexRoute: ForecastsIndexRoute,
  NotificationsIndexRoute: NotificationsIndexRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
