DROP POLICY IF EXISTS "Allow all to read cryptotokens" ON public.cryptotokens;
DROP POLICY IF EXISTS "Allow read access to cryptotokens" ON public.cryptotokens;

DROP TABLE IF EXISTS public.cryptotokens;

CREATE TABLE public.cryptotokens (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  token_name text NOT NULL UNIQUE
);

ALTER TABLE public.cryptotokens ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow read access to cryptotokens"
  ON public.cryptotokens
  AS PERMISSIVE
  FOR SELECT
  TO anon, authenticated
  USING (true);

GRANT ALL ON TABLE public.cryptotokens TO anon;
GRANT ALL ON TABLE public.cryptotokens TO authenticated;
GRANT ALL ON TABLE public.cryptotokens TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.cryptotokens_id_seq TO anon;
GRANT USAGE, SELECT ON SEQUENCE public.cryptotokens_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.cryptotokens_id_seq TO service_role;

COMMENT ON TABLE public.cryptotokens IS 'Tokens for which forecasts can be generated; admin inserts from API, then forecast is generated per token.';
